### ISSUE TITLE
login -> redirect home page as like spa

### ISSUE THREAD

**Issue by mostafa6765** [drehimself/inertia-example#1]
Can you share your opinion on how to implement login successfully then redirect home page as like vue spa project?
login.vue

**Comment by connecteev** [comment]
@mostafa6765 did you figure this out, and would you be able to share some sample code for auth and the redirect (that you mentioned above)?

**Comment by mostafa6765** [comment]
```js
  methods: {
    login: function () {
      axios.get('api/u/login', {
        params: {
          email: this.email,
          password: this.password
        }
      })
       .then(response=>{
         this.$cookies.set('authtoken', response.data, {
          path: '/',
          maxAge: 60 * 60 * 24 * 7
        })
         this.$router.push('/');
       })
    }
  }
```

* [cookie-universal-nuxt module for cookie server-side and client-side](https://www.npmjs.com/package/cookie-universal-nuxt)

That is sample code.

**Comment by mostafa6765** [comment]
you can get more idea about inertia here - [pingcrm login system](https://github.com/inertiajs/pingcrm/blob/master/resources/js/Pages/Auth/Login.vue#L53)
