### ISSUE TITLE
Inject no longer supported

### ISSUE THREAD

**Issue by matthew-spire** [drehimself/inertia-example#2]
If you're using the latest version of Inertia, the

<script>
export default {
  inject: ['page'],
}
</script>

which is located in Layout.vue, is no longer supported and-or necessary. In fact, it throws a Vue error.

**Comment by connecteev** [comment]
+1 I see the same thing when I go to any page, like http://127.0.0.1:8000/about, http://127.0.0.1:8000/users etc.

```
[Vue warn]: Injection "page" not found

found in

---> <Layout> at resources/js/Shared/Layout.vue
       <About> at resources/js/Pages/About.vue
         <Inertia>
           <Root>
```

**Comment by drehimself** [comment]
Fixed, thanks for the heads up!

**Comment by connecteev** [comment]
@drehimself thanks! Does the fix for this problem https://github.com/drehimself/inertia-example/commit/e65d81233970fda34234f2f2fb01a6d1b20e7cd9

involve removing this?
```
<script>
export default {
  inject: ['page'],
}
</script>
```

Btw, what was the issue caused by the spinner? Looks like you removed it..FWIW the spinner works fine for me.
